### ISSUE TITLE
MP3 Download via Web

### ISSUE THREAD

**Issue by thomasjefferson1743** [podverse/podverse-web#1099]
I work out a lot and would like to listen to podcasts on a lightweight MP3 player, a mobile phone is too big, bulky and heavy for wearing while working out. It would be great if I can download podcasts thru the web interface so that I can transfer them to a MP3 player. Lightweight MP3 players are very common for people to workout because mobile phones are simply too heavy. Its way too difficult to transfer a MP3 from a Apple Device [closed ecosystem :-( ]to a MP3 player.

Is there a copyright issue, technical issue or development resource issue?

**Comment by mitchdowney** [comment]
@thomasjefferson1743 thanks for the feature request. Hmm the problem is that I don't think there is a standard way for all web browsers to let you download an mp3. Some will attempt to play the mp3 instead of letting you download it...I will have to do more research to see what our options are.

If you are aware of any websites that offer an mp3 download button that works on the devices you are looking for, that might help point us in the right direction of how to do it.

**Comment by thomasjefferson1743** [comment]
Thanks mitchdowney, even something like this here:

https://www.thehighersidechats.com/brook-hines-the-virtuous-triangle-template-vax-injury-intimidation-whistleblowing-on-the-left/


"Episode Download Instructions

For Desktop/Laptop Computer Users:

Right-Click on the below Episode Link button in this popup window. Then choose to save the linked file from the context menu that appears."

**Comment by mitchdowney** [comment]
@thomasjefferson1743 ok interesting. I see...THC is recommending special instructions for downloading the file. This is why we haven't added it already. This is useful though. I may just copy THC+ approach for handling this. Thanks so much for your help. I don't have a timetable for delivery as we have other major crashes to fix, but it should be pretty simple work. It would actually be a good first issue for an open source contributor to work on if anyone wants to take care of it.
