### ISSUE TITLE
Difficult to access parts of the site after registering

### ISSUE THREAD

**Issue by Siebe** [podverse/podverse-web#168]
Hi mitch, so I decided to give podverse a try a while ago after listening to some clips, which I found really handy. I registered, but felt kind of blocked after that and forgot about it a bit. I went back twice and realized that I might have found a UX bug. I'm not an UX guy but this is my report:

When I register and log in to podverse.fm, I expect to still be able to see the top/latest podcasts, episodes and clips that I saw on the page when I'm not logged in (or via private browser). Instead there is no clear way to get to these lists and the same buttons now only show my own subscribed content and nothing more.

I have since found the "all podcasts/subscribed" filter button, but for me that was totally not obvious.

**Comment by mitchdowney** [comment]
Hi Siebe! Thanks for the feedback. Now that you mention it that does seem like a bad UX for new users...especially because they won't have subscribed podcasts when they first sign up.

I'm actually supposed to do a round of UX improvements for the website tonight and will include this. I'm thinking of making the dropdown selector for All Podcasts/Subscribed a little bigger, and also switching the default for logged-in users to whatever the user previously had selected. If you have other ideas please let us know.

**Comment by mitchdowney** [comment]
Alright I went ahead and disabled the "use Subscribed filter by default for logged-in user" behavior. While I originally found this feature convenient, it seems unnecessary now because the site will remember what filters you last used in between page loads and use them by default anyway (unless you're in private browsing, it relies on cookies).

If you have a chance to test it and can let me know if it works I'd appreciate it.

https://github.com/podverse/podverse-web/commit/e63dfe8435f98b26c332276ab64acb8c73a4d6c7

**Comment by Siebe** [comment]
Thanks for the quick resolvement. Yes, the main issue is solved. When I now register a new account in a private window, I still see all the podcasts and other content. Not much seems to change now after login and that feels like regular behavior for a website/webapp although I stumbled on something related.

I stumbled upon a small side issue. It looks like you keep the filter setting saved purely by browser session. It's a bit weird that when I log out, the setting is still on "subscribed" and again empty screen. Plus when I log in other account the setting again still persists on "subscribed". Perhaps reset on logout, or save per account?

**Comment by mitchdowney** [comment]
@Siebe reseting the cookies on log out makes perfect sense to me. I went ahead and added a `deleteQueryCookies` to delete the cookies that save the query info. Please test it out when you have a chance.

https://github.com/podverse/podverse-web/pull/171/files#diff-39a82974f5cfcac9db6ceb717ffca998a12fee1038a0ce2d5315f8467560189bR155

**Comment by Siebe** [comment]
Sorry for the wait, checked and approved. Good work @mitchdowney ;)
