### ISSUE TITLE
Bug with reference to Episode media file

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#17]
With this clip from the JRE, apparently the file previously lived at this URL:

http://traffic.libsyn.com/joeroganexp/p824.mp3 

But now it lives at this URL (the last character before .mp3):

http://traffic.libsyn.com/joeroganexp/p824a.mp3

The result is the clip detail page cannot load the mp3.

Mp3 URL's changing seems to be an uncommon, but it can happen. It seems in the case of JRE they released an original version of episode 824 named p824.mp3, then released a second version  named p824a.mp3. [Rogan RSS](http://joeroganexp.joerogan.libsynpro.com/rss)

I wonder how or if we could automatically account for this scenario.

**Comment by scvnc** [comment]
mmmm.. yep I was afraid of this-- it's why a 'dumb' document-based model worked pretty well.  This gets complicated fast when trying to track specific episodes/podcasts.  It's not clear to me right now how to automatically account for this scenario

**Comment by scvnc** [comment]
I think the fundamental problem is that a lot of the data in this application works on is based on external data which is potentially unreliable.  Media hosting, podcast/info/data.

Perhaps in the case of an episode: the GUID in the item may have some psudo unique-ness to it and we could use that instead of the mediaURL.

Another thing to consider is the clip-changing consequences when the original release is removed/changed. In theory this could invalidate the clip too because the time stamps are changed.

Maybe keeping the mediaURL as the identifier is still useful and then if it is changed for future clips then maybe it could be 'reported' and a manual fix/consolidation could happen.

**Comment by mitchdowney** [comment]
Ah yeah. I'm not sure if the GUID provides that uniqueness or not, or if the GUID got updated along with mp3.

Yeah if the mp3 changes then we can't count on the clips having the correct start - end time anymore.

There is another more common use case, somewhat related to this, where an episode no longer is available in the feed. I'll create a separate issue for it...

**Comment by scvnc** [comment]
If we can have some trust that the podcast rss/url wont change as much, then that is sort of nice.  If the episodes get switched around, then I guess in theory it would be OK to have some duplicates if a clip is made with an old/removed version.

**Comment by mitchdowney** [comment]
I opened a new story to handle these situations #20
