### ISSUE TITLE
[podcast/episode filter] Provide the filterable properties.

### ISSUE THREAD

**Issue by scvnc** [podverse/podverse-web#2]
Ensure that there are fields inside the clip object so that we can do a query something like this:

Find all clips where `podcast.rss_url` equals 'http://supermariopodcast.net/rss'
Filter where `podcast.rss_url == 'http://supermariopodcast.net/rss'`

Find all clips where the episode mediaURL equals 'http://supermariopodcast.net/media/ep1.mp3'
Filter where `episode.mediaURL == 'http://supermariopodcast.net/media/ep1.mp3'`

This will cause duplicates if a podcast provides multiple mediaUrls for acc, mp3, ogg; so maybe there is a better identifier, maybe episode.title is good enough?  Using the mediaURL is nice because the clip would be very related to that. Something to dwell on and think about.  Regardless we have to provide something to filter on.

**Comment by mitchdowney** [comment]
The [feedURL](https://github.com/podverse/podverse/blob/master/podverse/Podcast.swift#L15) is the first required property of the Podcast class in the Swift app.

The [mediaURL](https://github.com/podverse/podverse/blob/master/podverse/Episode.swift#L22) is an optional property of the Episode class, but it should possibly be required since I can't think of a situation where we'd want to save an episode that doesn't have a valid media file URL.

I'm also not familiar with a feed of episodes that provides multiple mediaURLs for one episode. I've definitely seen podcasters with separate RSS feeds for mp3 / ogg / video, but not one feed with multiple different formats. It might exist somewhere though, I don't know.
