### ISSUE TITLE
Add / allow volume control  for non mobile view

### ISSUE THREAD

**Issue by djbrieck** [podverse/podverse-web#231]
Please consider adding in a volume slider that remembers where you set it. Some podcasts have audio levels to high to be accounted for using just the system level volume controls, especially on certain macs driving headphones really makes using the web app tough, with a-little too loud audio the cuts out instead of going lower at lowest system volume setting.

**Comment by mitchdowney** [comment]
Hey thanks for making an issue for this. It really helps a lot. A volume slider shouldn't be too difficult. My only hesitation is I'm not sure where's a good place for the volume slider to go...I guess I can put it in the bottom right corner with the other buttons, but it seems like kind of a lot going on over there. For big screens only though maybe that's not a problem. I should probably try to talk to a real UX designer to help redesign the whole UI soon. Anyway I'll try to add a volume over this weekend.

**Comment by mitchdowney** [comment]
@eurbasius this could be a nice feature to add. We could follow a pattern like [PodFriend](https://github.com/MartinMouritzen/Podfriend) uses, adding it to the right-side of the mini player:

![image](https://user-images.githubusercontent.com/2262919/136644701-432e7583-33b3-42c1-ba92-4c71e5c726e0.png)

So for us it could go in the upper row of buttons here:

![image](https://user-images.githubusercontent.com/2262919/136644843-d1212b2a-145e-4157-b90e-1d2cd6eef9a3.png)

Here's the acceptance criteria I can think of...

Feel free to skip the CSS styling if you want me to do it.

1) The player component itself is in podverse-ui, so there will need to be updates in both the ui and web repos.

2) Add the rc-slider package to podverse-ui.

3) Render an rc-slider component in the media player component, to the right of the top row of buttons like in the screenshot. Include both the Slider and the Range component (I think the Range component will show a Tooltip of the volume value 0-100).

4) The volume gets set in the [<FilePlayer> component in podverse-ui](https://github.com/podverse/podverse-ui/blob/master/src/components/Media/MediaPlayer/MediaPlayer.tsx#L464). It accepts a float from 0-1 I think.

5) On change of the Slider value, update the volume to the value 0-100.

6) Add a Font Awesome sound icon to the left of the slider. On press of the sound icon, mute the audio and change the icon to a muted sound icon.

7) Since we won't be able to fit the volume slider in all window widths, I think for now we can work around it by just hide it on small screen sizes. We can use a CSS media rule for that. I don't know exactly what window width we should hide it, but if you can make a guess and put a CSS rule in it for it that'd be great.

I think that's it. Let me know if you have any questions or want to pair on it.
