### ISSUE TITLE
Add support for more translations

### ISSUE THREAD

**Issue by NathanBnm** [podverse/podverse-web#565]
Hello! I'm the French contributor on Weblate. I noticed that some strings are not currently available for translation. Maybe you could add them :smile: Here is a non-exhaustive list:
- About page
- Membership page features detail table header (Features, Free, Premium)
- Terms of service page
- Support page
- Podcast categories
- Filters (All, Category, Subscribed) and Trending select (Top - All Time, etc) on every page (podcasts, episodes, clips, etc)
- Podcasts/Hosts selector on Search page
- Podcast page filters (Selected item is translated but not the options list)
- Login required modal action buttons (Close, Log in)
- Episode/Clip details three dots menu options
- Podcasts list "Latest episode: {date}" label
- "Skip to page" feature
- Contact e-mail body content as long as they explain what the user has to write in the e-mail
- "Try premium free for 3 months! $18 per year after that" in register modal
- "Please confirm your e-mail" modal close button

Would be great if you could translate the dates too. For example "Feb 17th 2022" would be "17 février 2022" in French.

I seems that your page titles doesn't properly support UTF-8. For example the "About" page in French is "À propos" but the displayed title is "propos". Same for "Épisodes" which becomes "pisodes".

Finally is there any way you can translate e-mails too?

**Comment by mitchdowney** [comment]
Hello @NathanBnm! Sorry for the delay on seeing this. Thank you SO much for the French translations! I should have the info and updates you need by this weekend.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/podverse/ has all the translations (for those coming here to look)

**Comment by mitchdowney** [comment]
@comradekingu sorry, finally catching up on Github notifications...the translations file for mobile are the same for iOS and Android. It's a React Native app, so both platforms use the same base translation file in the same repo.

**Comment by mitchdowney** [comment]
@NathanBnm @comradekingu 

I finally swept through and tried fixing everything you cited. Some of them seemed to have been fixed already...some I did not make translatable though, and I'll explain those first:

*Did NOT make translatable*
- Terms of service page - the only reason I didn't enable this is since the Terms of Service is legal text, and I think we need to be careful with asking for community contributions for this. 
- Podcast categories - I need to make some more programmatic changes for this one, so I'll handle this in a separate issue.
- Filters - same as podcast categories...will handle in a separate issue.
- Podcast page filters (Selected item is translated but not the options list) - same as Filters
- Episode/Clip details three dots menu options - same as above
- Contact e-mail body content as long as they explain what the user has to write in the e-mail - so...part of the problem here is if someone writes us in a non-English language, our core dev team won't be able to help them :( (except maybe for Greek as Creon speaks it). Not sure how to handle this...
- This one isn't in your list, but there will be a new Tutorials page with A LOT of text. I'd like to get that page done before including translations for it. I'm actually worried it may scare translators away to see that much text, so...not sure I even want to include it anytime soon.

*Did make translatable*
- About page
- Membership page features detail table header (Features, Free, Premium)
- Support page
- Podcasts/Hosts selector on Search page
- Login required modal action buttons (Close, Log in)
- Podcasts list "Latest episode: {date}" label
- "Skip to page" feature
- "Try premium free for 3 months! $18 per year after that" in register modal
- "Please confirm your e-mail" modal close button

Alright, I'll try to get through the other translation tickets I created this week. If you notice any other translations I missed, can you make a new issue for them? Thanks so much for your help 🙏

**Comment by mitchdowney** [comment]
https://github.com/podverse/podverse-web/pull/852
