### ISSUE TITLE
Nothing in "Sexuality"?

### ISSUE THREAD

**Issue by comradekingu** [podverse/podverse-web#567]
https://podverse.fm/podcasts?category=sexuality has no entries
whereas https://podverse.fm/podcast/GXXTk5i1El is in "fiction".

**Comment by mitchdowney** [comment]
Hah so...our categories are supposed to mirror the categories of Apple since they have mostly set the standard categories that the podcast ecosystem uses.

Right now the website only supports top-level categories, but does not support sub-categories. According to the Apple standard Sexuality is a sub-category of Health and Fitness, so it shouldn't be on the home page right now. I'll create a separate Github issue for "add sub-category support to categories filter", and remove Sexuality from the home page for now.

As for the podcast you linked, all the categories we use are self-identified by the podcaster. So if you check the RSS for that podcast, you can see "Fiction" is the only category they have listed. https://anchor.fm/s/27606860/podcast/rss
