### ISSUE TITLE
Embedded player: The episode length text is a button leading to nowhere

### ISSUE THREAD

**Issue by kbondarev** [podverse/podverse-web#874]
**Describe the bug**
The episode length text is a button, but this button when clicked provides no obvious function.

**To Reproduce**
1. Go to [here](https://jupiterbroadcasting.net/show/linux-unplugged/465/)
2. Hover over the length text - see pointer cursor
3. Click on it - nothing happens

**Expected behavior**
Should be just an un-clickable text. Unless there's some other behaviour that is not triggering.

**Screenshots**
<kbd>![podverse bug - total-time](https://user-images.githubusercontent.com/7018928/180271580-284ab249-382c-4922-800f-699b0fa1b119.gif)</kbd>

**Additional context**
[Add any other context about the problem here.](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/140)

**Comment by mitchdowney** [comment]
@kbondarev great catch. That button actually functions as a "resume from current live time" when the item being played is a livestream, but it shouldn't be a button when it's not a liveitem:

![CleanShot 2022-07-22 at 13 30 16](https://user-images.githubusercontent.com/2262919/180501849-d170632c-9bb1-4488-bdd0-50cb8e084050.gif)

Should be fixed in https://github.com/podverse/podverse-web/pull/876
